# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import auth_pb2 as auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pq_req = channel.unary_unary(
                '/AuthService/pq_req',
                request_serializer=auth__pb2.PQRequest.SerializeToString,
                response_deserializer=auth__pb2.PQResponse.FromString,
                )
        self.req_DH_params = channel.unary_unary(
                '/AuthService/req_DH_params',
                request_serializer=auth__pb2.DHParamsRequest.SerializeToString,
                response_deserializer=auth__pb2.DHParamsResponse.FromString,
                )
        self.check_authentication = channel.unary_unary(
                '/AuthService/check_authentication',
                request_serializer=auth__pb2.checkAuthRequest.SerializeToString,
                response_deserializer=auth__pb2.checkAuthResponse.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def pq_req(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def req_DH_params(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def check_authentication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pq_req': grpc.unary_unary_rpc_method_handler(
                    servicer.pq_req,
                    request_deserializer=auth__pb2.PQRequest.FromString,
                    response_serializer=auth__pb2.PQResponse.SerializeToString,
            ),
            'req_DH_params': grpc.unary_unary_rpc_method_handler(
                    servicer.req_DH_params,
                    request_deserializer=auth__pb2.DHParamsRequest.FromString,
                    response_serializer=auth__pb2.DHParamsResponse.SerializeToString,
            ),
            'check_authentication': grpc.unary_unary_rpc_method_handler(
                    servicer.check_authentication,
                    request_deserializer=auth__pb2.checkAuthRequest.FromString,
                    response_serializer=auth__pb2.checkAuthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def pq_req(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthService/pq_req',
            auth__pb2.PQRequest.SerializeToString,
            auth__pb2.PQResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def req_DH_params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthService/req_DH_params',
            auth__pb2.DHParamsRequest.SerializeToString,
            auth__pb2.DHParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def check_authentication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthService/check_authentication',
            auth__pb2.checkAuthRequest.SerializeToString,
            auth__pb2.checkAuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
