# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"5\n\x0e\x43ompleteNonces\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cnonce_server\x18\x02 \x01(\t\".\n\tPQRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\x04\x12\r\n\x05nonce\x18\x02 \x01(\t\"W\n\nPQResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\x04\x12\x1f\n\x06nonces\x18\x02 \x01(\x0b\x32\x0f.CompleteNonces\x12\t\n\x01p\x18\x03 \x01(\t\x12\t\n\x01g\x18\x04 \x01(\t\"Q\n\x0f\x44HParamsRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\x04\x12\x1f\n\x06nonces\x18\x02 \x01(\x0b\x32\x0f.CompleteNonces\x12\t\n\x01\x41\x18\x03 \x01(\t\"R\n\x10\x44HParamsResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\x04\x12\x1f\n\x06nonces\x18\x02 \x01(\x0b\x32\x0f.CompleteNonces\x12\t\n\x01\x42\x18\x03 \x01(\t\"E\n\x10\x63heckAuthRequest\x12\x1f\n\x06nonces\x18\x01 \x01(\x0b\x32\x0f.CompleteNonces\x12\x10\n\x08\x61uth_key\x18\x02 \x01(\t\"-\n\x11\x63heckAuthResponse\x12\x18\n\x10is_authenticated\x18\x01 \x01(\x08\x32\xa5\x01\n\x0b\x41uthService\x12!\n\x06pq_req\x12\n.PQRequest\x1a\x0b.PQResponse\x12\x34\n\rreq_DH_params\x12\x10.DHParamsRequest\x1a\x11.DHParamsResponse\x12=\n\x14\x63heck_authentication\x12\x11.checkAuthRequest\x1a\x12.checkAuthResponseB\x08Z\x06./grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./grpc'
  _globals['_COMPLETENONCES']._serialized_start=14
  _globals['_COMPLETENONCES']._serialized_end=67
  _globals['_PQREQUEST']._serialized_start=69
  _globals['_PQREQUEST']._serialized_end=115
  _globals['_PQRESPONSE']._serialized_start=117
  _globals['_PQRESPONSE']._serialized_end=204
  _globals['_DHPARAMSREQUEST']._serialized_start=206
  _globals['_DHPARAMSREQUEST']._serialized_end=287
  _globals['_DHPARAMSRESPONSE']._serialized_start=289
  _globals['_DHPARAMSRESPONSE']._serialized_end=371
  _globals['_CHECKAUTHREQUEST']._serialized_start=373
  _globals['_CHECKAUTHREQUEST']._serialized_end=442
  _globals['_CHECKAUTHRESPONSE']._serialized_start=444
  _globals['_CHECKAUTHRESPONSE']._serialized_end=489
  _globals['_AUTHSERVICE']._serialized_start=492
  _globals['_AUTHSERVICE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
