version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/default.conf
    depends_on:
      - gateway

  gateway:
    build:
      context: .
      dockerfile: Dockerfile

  redis:
    image: redis:latest

  req_pq:
    build:
      context: .
      dockerfile: auth/req_pq/Dockerfile

  req_DH_params:
    build:
      context: .
      dockerfile: auth/req_DH_params/Dockerfile