FROM golang:1.20-alpine

# Set the working directory
WORKDIR /app

# Set redis env vars
ENV AUTH_SERVER_HOST=auth-server
ENV AUTH_SERVER_PORT=9000

ENV REDIS_HOST=gateway_redis
ENV REDIS_PORT=6379
ENV REDIS_PASSWORD=SuperSecretSecureStrongPass

# Copy the code into the container
COPY . .

# Download the dependancies 
RUN go mod tidy  

# Build the application
RUN go build -o myapp

# Run the application
CMD ["./myapp"]