FROM golang:1.20-alpine

# Set the working directory
WORKDIR /app

# Set redis env vars
ENV AUTH_SERVER_HOST=auth-server
ENV AUTH_SERVER_PORT=9000

ENV POSTGRES_HOST= 
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=test 
ENV POSTGRES_DBNAME=users
ENV POSTGRES_PORT=5432
ENV POSTGRES_SSLMODE=disable
ENV POSTGRES_TIMEZONE=Asia/Tehran
# Copy the code into the container
COPY . .

# Download the dependancies 
RUN go mod tidy  

# Build the application
RUN go build -o myapp

# Run the application
CMD ["./myapp"]